language: php

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: TYPO3_VERSION=^7.6
    - php: 5.6
      env: TYPO3_VERSION=^7.6
    - php: 7.0
      env: TYPO3_VERSION=^7.6
    - php: 7.1
      env: TYPO3_VERSION=^7.6
    - php: 7.1
      env: TYPO3_VERSION=^8
    - php: 7.0
      env: TYPO3_VERSION=^8

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - "$HOME/.composer/cache"

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      - secure: "kL/JYOhoCmInyZYfY7xof/UMaah0jwVZno5ZfKHSHFViCRahGuT5wmLHTVpuUwB0WwJEYXKXH7hJIh+ByLUchoR/46cN9NH/KC1ESR2bXrqpNflCozKwfrC12/UgG58Nz9DD/4hOL0QbQA/x7kuR+Z+pMukE5maX03zUPEF2a45YSookbkqRoZq0XbTphsgaDutVNR99GNNJAfBNcGXG8AI7x35lsv1fgU4+cuv/wrdoWUHHKhif33wEImyuJi43jtKOYLXKwRHczplUJB0fEhexAsuk/T+Af+7pdQCc2Ll51/OqIA9agRmlxgonPFLCsSIfNb76BrTrmf9BezN187X7Qf9mh0kV7PvMru1R6syKfhzm+J9ix9ZxojRe7O/QDxseOIlCTsftf2QJ/9eyvJpNB84HXbWQQcrT4IbLMVFHzykkBZaKYn81EdaVAV5g7Yw+MXcfUH/kr6FhRHecyv6V3C64iIVzuWHucgWeAT97MS7r2c5jksWL8Rhac2vkcQjn92PHXmn5csxXmuT5wn7yUZ+yXQKtXgujvDH6nw8gnIwXK+SqztWksh+d0s6l1sXAlgQHPcpilAmhfJZ2lCVZNRwzA2XQuoFQTV9B0qQNcCsL8m//YkhNMQyZ43oSa7LMKZooeRtBPtuGzg9zKuQopjNL41hB0suHvLWHn9Y="

before_install:
  - composer self-update
  - phpenv config-rm xdebug.ini

before_script:
  - composer require typo3/cms=$TYPO3_VERSION --prefer-source
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - echo; echo "Running unit tests"; .Build/bin/phpunit --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/
  - echo; echo "Running php lint"; find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - echo; echo "Running PHP Coding Standards Fixer checks"; .Build/bin/php-cs-fixer fix --config=Build/.php_cs -v --dry-run --using-cache=no --path-mode=intersection `git diff --name-only --diff-filter=ACMRTUXB $COMMIT_RANGE`
