language: php

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: TYPO3_VERSION=^7.6
    - php: 5.6
      env: TYPO3_VERSION=^7.6
    - php: 7.0
      env: TYPO3_VERSION=^7.6
    - php: 7.1
      env: TYPO3_VERSION=^7.6
    - php: 7.1
      env: TYPO3_VERSION=^8
    - php: 7.0
      env: TYPO3_VERSION=^8

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - "$HOME/.composer/cache"

notifications:
  slack:
    secure: IU5+A5ULp63E2O3jbAKIgGiONs6oiKa3qbj92xA1cx04Fv2d9K5mA5WXb3xdROeVOhfqfS28fQB0qGDgkQBu2dsWuzU/fIhRxuez+TCvsObo31Gg33zrngCsZUwPjzqfP1kyST6esQq+mAoyxBeXpm1pQysDGH/GPq46n+M98hA0oWNG7s52uJhrTlUo9qx4MF2kXEeqqsmSTwJaACedXzaEwTREarc3suYh/Fg6+wzvqSlTlYt6KqkPNXgzwjAM9XdPj7ZeZjcNwKRqjLbG629uQ3qLo8cYr0kenwc1KJ43dh4IP0M9eMeo1AIQBuGAZzmCjXoaf3t/0x3AtqPFAD9WoJ+uGZsEJ8oqGV3Szzwe+j3uK4AmXbVTuKdh+yiRrDq01U6vy9A+EcDIqXmQPRT1f6xJsiXjBGSyU3MWsbw1cYXDpwIobcaHh6WyBLvnrhJSws3RgNrTMWgWewvOSqYi128ydzFgi7SI1XbhcJ3gQ9WFQ2gLGZBlTv6IlB6xnLnPDoxcSP8Y+3zPfrUNwdCmOfTeFqclkWNukoA842TNfIH+Zhu5S9S7kfIRamItjxjpcrf/a/LeMq5QiWDLOfnd9R578M0kcMNKV2zHttMQBF0++6AOj3bRMqTM/i0/PmbaNubkl4+VRZmUWSbyxFad8NFhdVR0TGgUP2ElDMA=
    on_success: change
    on_failure: always

before_install:
  - composer self-update

before_script:
  - phpenv config-rm xdebug.ini
  - composer require typo3/cms=$TYPO3_VERSION
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - 'echo; echo "Running unit tests"; .Build/bin/phpunit --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/'
  - 'echo; echo "Running php lint"; find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;'
  - 'echo; echo "Running PHP Coding Standards Fixer checks"; .Build/bin/php-cs-fixer fix --config=Build/.php_cs -v --dry-run --using-cache=no --path-mode=intersection `git diff --name-only --diff-filter=ACMRTUXB $COMMIT_RANGE`'
